PoulePhaseWebGame/CompetitionGameWebSite/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CompetitionGameWebSite.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PoulePhaseWebGame/CompetitionGameWebSite/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System;

namespace CompetitionGameWebSite.Pages
{
    public class IndexModel : PageModel
    {
        
        private readonly ILogger<IndexModel> _logger;
        protected string baseApiAddress = "https://localhost:44308/api";
        public string leagueStatsJson;
        public string teamsJson;
        public JObject leagueStatsDynamic;
        public List<JObject> jsonobjects;

        public bool showScorePanel;
        public List<JObject> apiResults;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            leagueStatsJson = new WebClient().DownloadString($"{baseApiAddress}/HistoryStats");
            teamsJson = new WebClient().DownloadString($"{baseApiAddress}/teams");
            leagueStatsDynamic = JObject.Parse(leagueStatsJson);
            var deserializedteamsJson = JsonConvert.DeserializeObject<List<string>>(teamsJson);
            jsonobjects = (from item in deserializedteamsJson
                                         select JObject.Parse(item)).ToList();
        }

        public void OnPostSimulate(string[] AreChecked, string[] jsonObj, IFormCollection form, int? page)
        {
            leagueStatsJson = new WebClient().DownloadString($"{baseApiAddress}/HistoryStats");
            leagueStatsDynamic = JObject.Parse(leagueStatsJson);

            var requestingObj = new JObject();
            var requestingObjTeams = new JArray();
            foreach (var checkedItem in AreChecked)
            {
                var teamnumber = Convert.ToInt32(checkedItem);
                JObject item = JObject.Parse(jsonObj[teamnumber]);
                requestingObjTeams.Add(item);
            }
            requestingObj.Add("teams", requestingObjTeams);
            requestingObj.Add("historyleaguestats", leagueStatsDynamic);
            string dataJson = requestingObj.ToString();

            var httpWebRequest = (HttpWebRequest)WebRequest.Create($"{baseApiAddress}/Competition");
            httpWebRequest.ContentType = "application/json";
            httpWebRequest.Method = "POST";

            using (var streamwriter = new StreamWriter(httpWebRequest.GetRequestStream()))
            {
                streamwriter.Write(dataJson);
            }



            var httpResponse = (HttpWebResponse)httpWebRequest.GetResponse();
            string apiResult;
            using (var streamReader = new StreamReader(httpResponse.GetResponseStream()))
            {
                apiResult = streamReader.ReadToEnd();
            }
            var deserialisedApiJson = JsonConvert.DeserializeObject<List<string>>(apiResult);


            showScorePanel = true;
            jsonobjects = (from item in jsonObj
                           select JObject.Parse(item)).ToList();
                

            apiResults = (from item in deserialisedApiJson
                          select JObject.Parse(item)).ToList();
        }
    }
}

PoulePhaseWebGame/CompetitionGameWebSite/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace CompetitionGameWebSite.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PoulePhaseWebGame/CompetitionGameWebSite/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";

}

<div class="text-center">
    <h1 class="display-4">Welcome to the Round Robin Poule Simulator</h1>
    <p class="text-left">
        This is a simulator of the Eredivisie, using statistics of the year 2018/2019.
        Below you'll see a set of strengths and defenses, all calculated via the <link href="https://help.smarkets.com/hc/en-gb/articles/115001457989-How-to-calculate-Poisson-distribution-for-football-betting">Poission distribution</link> setup. <br />
        For example, Ajax made 70 goals at home, during 17 home games, which results in 70<span>&#247;</span>17 = 4,1176470588235294117647058823529 as "Home Attack Strength".
        This is done with all the teams in regards to:
        <ol>
            <li>Home Attack Strength (Home Goals made <span>&#247;</span> Home matches</li>
            <li>Home Defense Strength (Home Goals against <span>&#247;</span> Home matches</li>
            <li>Away Attack Strength (Home Goals made <span>&#247;</span> Away matches</li>
            <li>Away Defense Strength (Home Goals against <span>&#247;</span> Away matches</li>
        </ol>
    </p>
    <p class="text-left">
        In this poule setup, teams that are matched are getting their home and away strengths matched: A Home team can score as strong as the defenses' away team defense strength and visa versa.<br />
        Select an even number of teams (4 by default) and press 'Simulate' to use the competition simulator!
    </p>
    </p>
    <div>
        <form id="simulatePanel" class="simulation" asp-page-handler="Simulate" method="post">
            <div class="teams">
                <table align="center">
                    <tr>
                        <th></th>
                        <th>Team Name</th>
                        <th>Home Attack Strength</th><th>Home Defense Strength</th><th>Away Attack Strength</th><th>Away Defense Strength</th>
                    </tr>
                    @for (int i = 0; i < Model.jsonobjects.Count; i++)
                    {
                        var tmp = "[" + i + "].AreChecked";
                        var defaultcheck = i >= 0 && i < 4 ? true : false;
                        var obj = Model.jsonobjects[i];
                    <tr>
                        <td>
                            <input class="teamSelect" name="AreChecked" id="@tmp" type="checkbox" value="@i" checked="@defaultcheck" />
                        </td>
                        <td align="left"><input name="jsonObj" type="hidden" id="@i" value="@obj" />@obj["teamName"].ToString()</td>
                        <td>@obj["homeStats"]["AttackStrength"]</td>
                        <td>@obj["homeStats"]["DefenseStrength"]</td>
                        <td>@obj["awayStats"]["AttackStrength"]</td>
                        <td>@obj["awayStats"]["DefenseStrength"]</td>
                    </tr>
                    }
                </table>
            </div>
            <div class="stats">
                <h2>Global statistics</h2>
                <table align="center" title="League Statistics">
                    @foreach (var obj in Model.leagueStatsDynamic)
                    {
                        <tr>
                            <td>@obj.Key</td>
                            <td>@obj.Value</td>
                        </tr>
                    }
                </table>
            </div>
            <button id="simulateTeams" class="btn btn-primary" type="submit">Simulate</button>
        </form>
    </div>
    @if (Model.showScorePanel)
    {
        <div id="scorePanel">
            <div class="Results">
                <h2>Poule matches</h2>
                <table>
                    @foreach (var pouleresult in Model.apiResults)
                    {
                        <tr>
                            <td align="left">@pouleresult["ToString"]</td>
                        </tr>
                    }
                </table>
            </div>

            <div class="Compstats">
                <h2>Competition Results</h2>
                <table>
                    <tr>
                        <th>Team Name</th>
                        <th>Poule Points</th>
                        <th>Goals For</th>
                        <th>Goals Against</th>
                        <th>Goal Difference</th>
                    </tr>
                    @foreach (var pouleresult in Model.apiResults)
                    {

                        @if (pouleresult.ContainsKey("Key"))
                        {
                            <tr>
                                <td align="left">@pouleresult["Key"]["teamName"]</td>
                                <td>@pouleresult["Value"]["pouleStance"]</td>
                                <td>@pouleresult["Value"]["goalsFor"]</td>
                                <td>@pouleresult["Value"]["goalsAgainst"]</td>
                                <td>@pouleresult["Value"]["goalDifference"]</td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>
    }
</div>

PoulePhaseWebGame/CompetitionGameWebSite/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CompetitionGameWebSite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CompetitionGameWebSite</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CompetitionGameWebSite - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>